language: python

python:
    - "3.6"

cache: pip

addons:
    chrome: stable

services:
  - xvfb

notifications:
    email: false

install: 
    - make chromedriver
    - make pipenv

jobs:
    include:
        - stage: 888sport
          script:
            # can't use for mark 888sport or _888sport
            - xvfb-run pipenv run pytest -m eight88sport --proxy $PROXY
        - stage: bet365
          script:
            - xvfb-run pipenv run pytest -m bet365
        - stage: bwin
          script:
            - xvfb-run pipenv run pytest -m bwin
        - stage: williamhill
          script:
            - xvfb-run pipenv run pytest -m williamhill
        - stage: upload coverage
          script:
            # Upload coverage to Codacy
            - make coverage  
