language: python

python:
  - "3.6"

cache: pip

addons:
  chrome: stable

notifications:
  email: false

install: 
  - make chromedriver
  - make pipenv

jobs:
  include:
    - script: pipenv run pytest -m eight88sport --proxy $PROXY
    - script: pipenv run pytest -m bet365
    - script: pipenv run pytest -m bwin
    - script: pipenv run pytest -m williamhill
    - stage: coverage
      script: make coverage
