language: python

python:
  - "3.6"

cache: pip

addons:
  chrome: stable

notifications:
  email: false

install: 
  - make chromedriver
  - make pipenv

jobs:
  include:
    - script: 
      - make test
      - make coverage
