language: python

python:
    - "3.6"

addons:
    chrome: stable

notifications:
    email: false

install:
    # Install ChromeDriver
    - wget -N https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

    # Install pipenv
    - pip install pipenv --upgrade
    - pipenv install --dev --skip-lock

jobs:
    include:
        - stage: 888sport
          script:
            # can't use for mark 888sport or _888sport
            - pipenv run pytest -m eight88sport
        - stage: bet365
          script:
            - pipenv run pytest -m bet365
        - stage: bwin
          script:
            - pipenv run pytest -m bwin
        - stage: williamhill
          script:
            - pipenv run pytest -m williamhill

after_success: 
    # Upload coverage to Codacy
    - pipenv run python-codacy-coverage -r coverage.xml

