language: python
python:
  - "3.6"

addons:
    chrome: stable

notifications:
    email: false

install:
    # Install ChromeDriver
    - wget -N https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

    # Install pipenv
    - pip install pipenv --upgrade
    - pipenv install --dev --skip-lock


jobs:
    include:
    - stage: test
      script:
          - pipenv run pytest
    - stage: coverage
      script:
          - pipenv run python-codacy-coverage -r coverage.xml
