language: python

python:
  - "3.6"

cache: pip

addons:
  chrome: stable

notifications:
  email: false

install: 
  - make chromedriver
  - make pipenv

jobs:
  include:
    - script: 
      - pipenv run pytest -m eight88sport --proxy $PROXY
      - pipenv run pytest -m bet365
      - pipenv run pytest -m bwin
      - pipenv run pytest -m williamhill --proxy $PROXY
      - pipenv run pytest --ignore=aao/test/spiders/bookmakers
      - make coverage
